---
title: "Biosys Turtles Requirements"
author: "Dept Parks & Wildlife"
date: "20/04/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
setwd("~/projects/turtle-scripts/wastd")
if (file.exists("../config/setup.R")) source("../config/setup.R")
if (file.exists("../config/load.R")) source("../config/load.R")
```

# Data

```{r prepare_data}
#------------------------------------------------------------------------------#
# Helper functions
#
#' Map given function, handle null as NA and flatten_chr()
map_chr_hack <- function(.x, .f, ...) {
  map(.x, .f, ...) %>% map_if(is.null, ~ NA_character_) %>% flatten_chr()
}

as_url <- function(url, label) {
  paste0("<a href=\"", url, "\" target=\"_\">", label, "</a>")
}

md_to_html <- function(md) {
  if (is.null(md) || is.na(md)) md <- "no content"
  markdown::markdownToHTML(file = NULL, text = md, fragment.only = TRUE)
}

extract_name <- function(x, n) sapply(x, `[[`, n)

extract_related <- function (x) {
  out <- x %>% 
  str_extract_all("(?<=#)\\d+(?=\\s|\\n|\\<|$)") %>% 
  compact %>% 
  unlist %>% 
  extract_name(1) %>% 
  as.integer %>% 
  compact
  if (length(out) == 0) return(NA_integer_) else return(out)
} 
# extract_related("#5 #65 #123 #7# #test # test ## #8\n#9")
testthat::expect_equal(extract_related("#5 #65 #123 #7# #test # test ## #8\n#9"), c(5, 65, 123, 8, 9))
testthat::expect_equal(extract_related("#7# #test # test ## "), NA_integer_)
testthat::expect_equal(extract_related(""), NA_integer_)


#------------------------------------------------------------------------------#
# Settings
#
gh_issues_url <- "/repos/parksandwildlife/biosys-turtles/issues"
gh_projects_url <- "/repos/parksandwildlife/biosys-turtles/projects"
gh_milestones_url <- "/repos/parksandwildlife/biosys-turtles/milestones"
gh_labels_url <- "/repos/parksandwildlife/biosys-turtles/labels"

#------------------------------------------------------------------------------#
# Load data
# Following https://github.com/jennybc/analyze-github-stuff-with-r
issue_list <- gh(gh_issues_url, state = "all", .limit = Inf)
# str(issue_list)
# listviewer::jsonedit(issue_list)

# https://developer.github.com/v3/projects/
# Requires custom Accept header
#project_list <- gh(gh_projects_url, state = "all", .limit = Inf,
#                   .send_headers = c(
#                     Accept = "application/vnd.github.inertia-preview+json"))
#listviewer::jsonedit(project_list)

milestone_list <- gh(gh_milestones_url, state = "all", .limit = Inf)
# listviewer::jsonedit(milestone_list)

labels_list <- gh(gh_labels_url, state = "all", .limit = Inf)


#------------------------------------------------------------------------------#
# Transform data
issues <- issue_list %>% {
    tibble::tibble(
      id = map_int(., "number"),
      title = map_chr(., "title"),
      body = map_chr_hack(., "body") %>% map(md_to_html),
      related = body %>% map(extract_related),
      state = map_chr(., "state"),
      html_url = map_chr(., "html_url") %>% map(as_url, "View"),
      comments_url = map_chr(., "comments_url") %>% map(as_url, "View"),
      labels_url = map_chr(., "labels_url") %>% map(as_url, "View"),
      labels = map(., "labels") %>% map(extract_name, "name"),
      created_by = map_chr(., c("user", "login")),
      assignee = map_chr(., c("assignee", "login")),
      milestone = map_chr(., c("milestone", "title")),
      created_at = map_chr(., "created_at") %>% as.Date(),
      updated_at = map_chr_hack(., "updated_at") %>% as.Date(),
      due_at = map_chr_hack(., "due_on") %>% as.Date(),
      closed_at = map_chr_hack(., "closed_at") %>% as.Date()
    )
  } %>% 
    arrange(id) #%>%
    # separate_rows(labels) %>%
    # mutate(tagslog = TRUE) %>%
    # spread(labels, tagslog, fill = FALSE) %>%
    # select(-c, -ready, -have, -Requirement)

# str(issues)
# View(issues)
i <- issues %>% separate_rows(labels) %>% mutate(tagslog = TRUE) %>%
    spread(labels, tagslog, fill = FALSE)  %>%
    select(id, Stakeholder, Functional, Transition, must, should)

iss <- left_join(issues, i, by = "id")
names(i)
milestones <- milestone_list %>% {
    tibble::tibble(
      id = map_int(., "number"),
      title = map_chr(., "title"),
      description = map_chr_hack(., "description"),
      state = map_chr(., "state"),
      html_url = map_chr(., "html_url"),
      labels_url = map_chr(., "labels_url"),
      created_by = map_chr(., c("creator", "login")),
      created_at = map_chr(., "created_at") %>% as.Date(),
      updated_at = map_chr_hack(., "updated_at") %>% as.Date(),
      due_at = map_chr_hack(., "due_on") %>% as.Date(),
      closed_at = map_chr_hack(., "closed_at") %>% as.Date()
    )
  }
# str(milestones)
# View(milestones)

labels <- labels_list %>% {
  tibble::tibble(
    id = map_int(., "id"),
    url = map_chr(., "url") %>% map(as_url, "View requirements"),
    name = map_chr(., "name"),
    colour = map_chr(., "color")
  )
}

```

## Business needs

```{r business_needs_table, echo=FALSE}
DT::datatable(milestones)
```

## Requirements

```{r requirements_table, echo=FALSE}
DT::datatable(issues)
```



```{r}
library(networkD3)

relations <- issues %>% 
  select(id, related) %>% 
  filter(!is.na(related)) %>% 
  rowwise() %>% 
  do(expand.grid(.$id, .$related)) %>%
  transmute(source = Var1 - 1, 
            target = Var2 - 1)
relations

forceNetwork(
  Links = data.frame(relations),
  Nodes = data.frame(issues),
  Source = "source", 
  Target = "target",
  Value = 1, 
  NodeID = "id",
  Group = "milestone", 
  opacity = 0.8,
  fontSize = 10,
  legend = TRUE, 
  arrows = TRUE,
  bounded = FALSE,
  zoom = TRUE)

# Flare <- jsonlite::fromJSON(
#   "https://cdn.rawgit.com/christophergandrud/networkD3/master/JSONdata/flare.json", 
#   simplifyDataFrame = FALSE)
# Flare$children = Flare$children[1:3]
# diagonalNetwork(List = Flare, fontSize = 10, opacity = 0.9)

```
