source("config/setup.R")
setwd("~/projects/turtle-scripts")
ckanr::resource_update(ETL_RID, "ningaloo/ningaloo_etl.html")
ckanr::resource_update(SPM_RID, "ningaloo/spatial_modelling.html")
ckanr::resource_update(W2_ETL_RID, "wamtram/wamtram_etl.html")
ckanr::resource_update(TRACKS_RID, "wastd/tracks.html")
