---
title: "Port Hedland Preview"
author: "Care for Hedland with North West Shelf Flatbacks WA"
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    fig_width: 10
    fig_height: 6
    code_folding: hide
    theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("wa-turtle-programs/tracks_helpers.R"))
library(sf)
library(turtleviewer)
data("turtledata", package = "turtleviewer")
x <- filter_data_odkc(turtledata, area_name = "Port Hedland")
s <- x$sites %>% dplyr::filter(site_id == 141)
```

The data shown here was downloaded from ODK Central on `r turtledata$downloaded_on`.

# Maps
## Turtle tracks and nests
```{r}
x$tracks %>% 
  filter_pth_spoilbank() %>%  
  map_tracks_odkc(sites=s) %T>% 
  mapview::mapshot(file=here::here("wa-turtle-programs/PTH_spoilbank_tracks.png"))
```

## Marine Wildlife Incidents
```{r}
x$mwi %>% 
  filter_pth_spoilbank() %>% 
  map_mwi_odkc(sites=s) %T>% 
  mapview::mapshot(
    file=here::here("wa-turtle-programs/PTH_spoilbank_strandings.png")
  )
```

# Data

## Turtle tracks and nests
```{r}
x$tracks %>% 
  filter_pth_spoilbank() %>% 
  wastdr::sf_as_tbl() %>% 
  reactable::reactable()

x$tracks %>% 
  filter_pth_spoilbank() %>% 
  sf_as_tbl %>% 
  readr::write_csv(path=here::here("wa-turtle-programs/PTH_spoilbank_tracks.csv"))
```

## Marine Wildlife Incidents
```{r}
x$mwi %>% 
  filter_pth_spoilbank() %>% 
  wastdr::sf_as_tbl() %>% 
  reactable::reactable()

x$mwi %>% 
  filter_pth_spoilbank() %>% 
  sf_as_tbl %>% 
  readr::write_csv(path=here::here("wa-turtle-programs/PTH_spoilbank_strandings.csv"))

tracks_gj <- x$tracks %>% geojsonsf::sf_geojson()
mwi_gj <- x$mwi %>% geojsonsf::sf_geojson()
```

