knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
# devtools::install_github('Ather-Energy/ggTimeSeries')
library(here)
library(wastdr)
library(dplyr)
library(purrr)
library(tidyr)
library(magrittr)
library(skimr)
library(leaflet)
library(RColorBrewer)
library(lubridate)
library(listviewer)
library(DT)
library(ggplot2)
library(ggTimeSeries)
library(ckanr)
library(googledrive)
library(ggmap)
library(gganimate)
library(ggalt)
library(ggTimeSeries)
# Configure ckanr to data.dpaw.wa.gov.au with env vars from .Renviron
ckanr::ckanr_setup(url = Sys.getenv("CKAN_URL"), key = Sys.getenv("CKAN_API_KEY"))
