---
title: "Turtle Nesting Census Previews 2019-20"
author: "Flatbacks WA, DBCA"
date: "`r Sys.Date()`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: spacelab
    social: menu
    source_code: https://git.io/vaZdx
    self_contained: true
---


```{r global}
library(flexdashboard)
library(tidyverse)
library(knitr)
library(DT)
library(reactable)
library(fs)
library(googledrive)
library(leaflet)
library(ckanr)
library(wastdr)
library(ruODK)

source(here::here("wa-turtle-programs", "tracks_helpers.R"))
load_saved_data()
```

Sidebar {.sidebar}
=======================================================================

### Location
Select location.

### Time
Filter to a date range.
Presets: Current season, current month, current week, yesterday.

### Species
Filter to a species.

### Download
Download the data shown.

```{r, eval=F}
# Rate at which to flag high download traffic
sliderInput("rateThreshold", "Warn when rate exceeds:",
            min = 0, max = 50, value = 3, step = 0.1
)
# Maximum number of raw data rows to keep
numericInput("maxrows", "Recent downloads window:", 50)
```


Dashboard
=======================================================================

Row {data-height=150}
-----------------------------------------------------------------------

### Tracks & Nests {.value-box}

```{r}
no_tracks <- tracks %>% nrow
valueBox(no_tracks, icon = "fa-shoe-prints")
```

### Strandings {.value-box}

```{r}
no_mwi <- mwi %>% nrow
valueBox(no_mwi, icon = "fa-dizzy")
```

### Disturbances {.value-box}

```{r}
no_dist <- dist %>% nrow
valueBox(no_dist, icon = "fa-paw")
```

### Flatback nesting success

```{r}
nesting <- tracks %>%
  dplyr::mutate(season=2019) %>%
  wastdr::nesting_type_by_season_species() %>%
  dplyr::mutate(
    nesting_success_rate = (
      `successful-crawl` /
        (`false-crawl` + `track-not-assessed` + `track-unsure`)
    )
  )

ns <- nesting %>% dplyr::filter(species == 'natator-depressus')

flexdashboard::gauge(
  round(ns$nesting_success_rate * 100, 2), min = 0, max = 100, symbol = '%',
  gaugeSectors(success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
  ))
```

Row
-----------------------------------------------------------------------

```{r data_map}
# tracks %>%
#   dplyr::mutate(
#     datetime = observation_start_time,
#     name="",
#     observer=reporter,
#     survey_id="TBA",
#     site_name="TBA",
#     survey_start_time=datetime,
#     survey_end_time=datetime,
#     absolute_admin_url=NA
#     ) %>%
#   wastdr::map_tracks(cluster = T)

```


